# Generated by Django 4.2.9 on 2024-01-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('required_arrival_date_time', models.DateTimeField()),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('special_request', models.CharField(blank=True, max_length=255, null=True)),
                ('shared', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('owner_passenger_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_driver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=255)),
                ('max_passengers', models.IntegerField()),
                ('special_vehicle_info', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='RideSharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_num', models.IntegerField()),
                ('rideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_app.ride')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_driven', to='uber_app.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_owned', to='uber_app.user'),
        ),
    ]
