# Generated by Django 4.2.9 on 2024-02-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
