# Generated by Django 4.2.9 on 2024-02-01 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uber_app', '0002_alter_user_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
