# Generated by Django 4.2.9 on 2024-02-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0003_alter_ride_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ownerID',
            field=models.BigIntegerField(),
        ),
    ]
