# Generated by Django 4.2.9 on 2024-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_app', '0012_auto_20240207_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
